"""Buzz local browser control center."""
def dashboard_html()->str:
    return r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Buzz Control Center</title>
<style>body{margin:0;background:#090b10;color:#f5f7fb;font-family:system-ui,-apple-system,Segoe UI,sans-serif}.wrap{max-width:1050px;margin:auto;padding:36px 22px}.top{display:flex;justify-content:space-between;align-items:center}.brand{font-size:42px;font-weight:800}.online{color:#9ee6b0}.panel{margin-top:20px;padding:24px;border:1px solid #252b36;border-radius:20px;background:#11151d}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card{padding:15px;border:1px solid #252b36;border-radius:14px;background:#0d1118}.muted{color:#9aa4b5}.row{display:flex;gap:10px;flex-wrap:wrap}input{flex:1;min-width:210px;padding:13px;border-radius:12px;border:1px solid #303848;background:#090c12;color:#fff;font-size:16px}button{padding:12px 17px;border:0;border-radius:12px;font-weight:700;cursor:pointer}.primary{background:#f2f4f8;color:#0b0d12}.approve{background:#9ee6b0;color:#07110a}.answer,.pending{white-space:pre-wrap;margin-top:15px}.pending .card{margin-top:10px}.foot{margin-top:20px;color:#768196;font-size:13px}</style></head><body><main class="wrap"><div class="top"><div class="brand">BUZZ</div><div class="online">● Local server online</div></div>
<section class="panel"><h1>Buzz Control Center</h1><div class="grid"><div class="card"><b>AI Core</b><div class="muted">Planning + routing</div></div><div class="card"><b>Security</b><div class="muted">Approvals + audit</div></div><div class="card"><b>Computer</b><div class="muted">Apps, files + commands</div></div><div class="card"><b>Integrations</b><div class="muted">Trading, DevOps + Home</div></div></div></section>
<section class="panel"><h2>Talk to Buzz</h2><div class="row"><input id="token" type="password" placeholder="Local BUZZ_API_TOKEN"><input id="message" maxlength="4000" placeholder="Ask Buzz to do something..."><button class="primary" id="send">Send</button></div><div id="answer" class="answer"></div><div id="pending" class="pending"></div><div class="foot">The token remains in this page only. Critical actions still require explicit approval.</div></section><div class="foot">Buzz v0.1 • Port 8787</div></main>
<script>
const $=id=>document.getElementById(id), send=$("send"), msg=$("message"), token=$("token"), answer=$("answer"), pending=$("pending");
function headers(){return {"Content-Type":"application/json","Authorization":"Bearer "+token.value}}
async function approveAction(action,button){button.disabled=true;button.textContent="Approving…";try{const r=await fetch("/approve",{method:"POST",headers:headers(),body:JSON.stringify({skill:action.skill,arguments:action.arguments,approval_token:action.approval_token})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Approval failed");button.textContent=d.success?"Executed ✓":"Failed";answer.textContent=d.message||answer.textContent;}catch(e){button.disabled=false;button.textContent="Approve";answer.textContent=e.message}}
function renderPending(items){pending.innerHTML="";for(const action of items||[]){const card=document.createElement("div");card.className="card";const title=document.createElement("b");title.textContent="Approval required: "+action.skill;const reason=document.createElement("div");reason.className="muted";reason.textContent=action.reason||"Buzz requires confirmation before executing this action.";const button=document.createElement("button");button.className="approve";button.textContent="Approve";button.addEventListener("click",()=>approveAction(action,button));card.append(title,reason,document.createElement("br"),button);pending.appendChild(card)}}
async function ask(){const text=msg.value.trim();if(!text)return;send.disabled=true;answer.textContent="Buzz is thinking…";pending.innerHTML="";try{const r=await fetch("/request",{method:"POST",headers:headers(),body:JSON.stringify({text,source:"dashboard"})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Request failed");answer.textContent=d.text||"Done.";renderPending(d.metadata&&d.metadata.pending_confirmation)}catch(e){answer.textContent=e.message}finally{send.disabled=false}}
send.addEventListener("click",ask);msg.addEventListener("keydown",e=>{if(e.key==="Enter")ask()});
</script></body></html>"""
